### PR TITLE
Fix #26

### LINKED ISSUE #26: Improve `has_*` vectorization
> @chainsawriot yes they should probably give `NA_logical_`. You wanna do that?

Yeah.

_Originally posted by @chainsawriot in https://github.com/schochastics/adaR/issues/3#issuecomment-1732640438_

### PR DESCRIPTION
**Pull request by chainsawriot**

### CODE REVIEW

**Comment by schochastics** [comment]
thanks!

**Comment by chainsawriot** [comment]
@schochastics More tests will be added later for the PR #3.

Suggestion:

1. Do you want to consolidate the documentation of all `ada_has_*` in one documentation.
2. I found that `utf8::as_utf8` is probably not needed on modern enough R. It can cut the running time by ~10%. But you would at least need to set the R requirement to 4.2 (for those using Windows).

**Comment by schochastics** [comment]
@chainsawriot 
1. yes. If you fix the NULL thing, do you mind doing that in the same PR?
2. Will think about that but I think it is a good idea. I also would like to get rid of the vapply for the length which is a runtime killer

**Comment by chainsawriot** [comment]
@schochastics Good, will do 1.

2. The length thing is partially fixed by calculating the char* length in C++.

**Pull request merged**
