### PR TITLE
add support for public suffix extraction #14

### PR DESCRIPTION
**Pull request by schochastics**
Sanity check with [psl package](https://github.com/hrbrmstr/psl).
``` r
urls <- c(
'https://subsub.sub.domain.co.uk/page?q=1234#abcd',
'https://domain.api.gov.uk/page?q=1234#abcd',
'https://domain.co.uk/page?q=1234#abcd',
'https://www.domain.com/page?q=1234#abcd',
'https://domain.com/page?q=1234#abcd'
)

adaR::public_suffix(urls)
#> [1] "co.uk"      "api.gov.uk" "co.uk"      "com"        "com"
hosts <- adaR::ada_get_hostname(urls)
psl::public_suffix(hosts)
#> [1] "co.uk"  "gov.uk" "co.uk"  "com"    "com"
```

<sup>Created on 2023-09-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The result from psl should be authoritative. api.gov.uk does appear in the psl list, but not sure why it is apparently not the right solution here

### CODE REVIEW

**Comment by schochastics** [comment]
I think we can make use of memoise here to speed up the lookup since we can expect a lot of the same input in "real" datasets

**Comment by schochastics** [comment]
missing all these cases:
```
*.kawasaki.jp
*.kitakyushu.jp
*.kobe.jp
*.nagoya.jp
*.sapporo.jp
*.sendai.jp
*.yokohama.jp
```

``` r
psl::public_suffix("https://www.takatoukiter.asakshfakjf.yokohama.jp")
#> [1] "asakshfakjf.yokohama.jp"
adaR::public_suffix("https://www.takatoukiter.asakshfakjf.yokohama.jp")
#> [1] "jp"
```

<sup>Created on 2023-09-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by schochastics** [comment]
- Not utf8 safe yet. 

- api.gov.uk remains a mystery. All parsers I tried return gov.uk although api.gov.uk is in the list

**Comment by chainsawriot** [comment]
@schochastics I tried this in Ruby (I think it is probably more authoritative than `psl` the R package, because GitHub Pages also uses `public_suffix`)

```rb
require 'uri/http'
require 'public_suffix'

def parse(url)
  uri = URI.parse(url)
  domain = PublicSuffix.parse(uri.host, ignore_private: true)
  puts domain.domain
  puts PublicSuffix.valid?(uri.host)
end

urls = ["https://www.takatoukiter.asakshfakjf.yokohama.jp",
        "https://domain.api.gov.uk/page?q=1234#abcd",
        "https://domain.com/page?q=1234#abcd",
        "https://blogspot.com"] ## private domain

for url in urls do
  parse(url)
end
```

`api.gov.uk` is indeed returned.

**Comment by chainsawriot** [comment]
```ruby
require 'uri/http'
require 'public_suffix'

def parse(url)
  uri = URI.parse(url)
  domain = PublicSuffix.parse(uri.host, ignore_private: true)
  puts domain.tld
  puts PublicSuffix.valid?(uri.host)
end

urls = ["https://www.takatoukiter.asakshfakjf.yokohama.jp",
        "https://domain.api.gov.uk/page?q=1234#abcd",
        "https://whatever.domain.com/page?q=1234#abcd",
        "https://a.b.c.kobe.jp/abc",
        "https://blogspot.com"] ## private domain

for url in urls do
  parse(url)
end
```

This one indeed gives `gov.uk`. ok, now I understand what the issue is.

**Comment by schochastics** [comment]
Thanks for the help. Need to rename it to tld_extract

**Comment by chainsawriot** [comment]
@schochastics It depends on the purpose. If what we want is `tld` (top-level domain), then I think "gov.uk" is probably correct (although I don't understand "asakshfakjf.yokohama.jp" as a top-level domain). However, if the purpose is to identify the registrar to whom the domain name "domain.api.gov.uk" is registered, then I think "api.gov.uk" is a better answer (and one can look at the list to see the contact person).

It's so [darn complicated](https://pkg.go.dev/golang.org/x/net/publicsuffix).

**Comment by schochastics** [comment]
@chainsawriot yeah it is crazy. Guess best case we can accomodate both cases or the case that the webtrack people need. Can you see how the rust lib gets gov.uk right? AFAIS all this libs just work with the dat file as input and dont know how they distinguish these two cases.

What you are wondering about are the wildcard cases. So there are tld *.kawasaki.jp and anything.kawasaki.jp is apparently a tld

**Comment by chainsawriot** [comment]
This (js) actually gives "api.gov.uk". I think there is no authoritative answer. I think what we can only say is "x compatible", e.g. libpsl compatible.

```js
var psl = require("psl");
var parsed = psl.parse('domain.api.gov.uk');
console.log(parsed.tld);
```

**Comment by chainsawriot** [comment]
Another simple option is to return TLD (the very strict one) and the matched entry in psl.

```r
adaR::extract_tld("https://www.takatoukiter.asakshfakjf.yokohama.jp") ## asakshfakjf.yokohama.jp
adaR::extract_psl_entry("https://www.takatoukiter.asakshfakjf.yokohama.jp") ## *.yokohama.jp
adaR::extract_tld("https://domain.api.gov.uk") ## gov.uk, libpsl compatible
adaR::extract_psl_entry("https://domain.api.gov.uk") ## api.gov.uk
```

**Comment by schochastics** [comment]
@chainsawriot ok then we stick with what we get out of the list for now (ie what we have). seems less painful.

**Comment by chainsawriot** [comment]
@schochastics Now I **REALLY** know what the problem is:

The psl is actually two lists.

* ICANN DOMAINS
* PRIVATE DOMAINS

"api.gov.uk" is actually in the private domains, and therefore should not be matched; therefore, "gov.uk" should the definitive correct answer. So, the js implementation is incorrect.

For us, the solution is to split the list into two.

**Comment by schochastics** [comment]
Dear lord thanks for the detective work. Then I split the file. Do we even need the private stuff?

**Comment by chainsawriot** [comment]
@schochastics Well, unless you want to check for the ICANN compliance. We can implement it when we need that. For now, [YAGNI](https://de.wikipedia.org/wiki/YAGNI).

**Comment by chainsawriot** [comment]
Of course, you can also have `adaR::public_suffix(domain, private = TRUE)`.

**Comment by schochastics** [comment]
> Of course, you can also have `adaR::public_suffix(domain, private = TRUE)`.

I will keep that for future work

**Pull request merged**
